"""add language to posts

Revision ID: 27338144af47
Revises: bdb790882228
Create Date: 2019-08-07 15:55:56.715972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27338144af47'
down_revision = 'bdb790882228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
